export enum Actions {
  SET_CIW = 'SET_CIW',
  CREATE_CIW = 'CREATE_CIW',
  UPDATE_CIW = 'UPDATE_CIW',
  DELETE_CIW = 'DELETE_CIW',
  CREATE_TEMPLATE = 'CREATE_TEMPLATE',
  DELETE_TEMPLATE = 'DELETE_TEMPLATE',
}
